export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE"
export const ADD_NEW_MESSAGE = "ADD_NEW_MESSAGE"
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT"